// ui/web/src/components/TreatsTabs.svelte
<p class="panel-tabs">
  <a class:is-active={all} on:click={() => switchTab(Tab.ALL)}>Все</a>
  <a class:is-active={discount} on:click={() => switchTab(Tab.DISCOUNTED)}>Со скидкой</a>
</p>

<script>
  import {createEventDispatcher} from "svelte"
  import {Tab} from "../const.js"

  const dispatch = createEventDispatcher()

  export let currentTab

  $: all = currentTab === Tab.ALL
  $: discount = currentTab === Tab.DISCOUNTED

  const switchTab = (tab) => {
    dispatch('switch', tab)
  }
</script>

// ui/web/src/components/TreatsTabs.vue
<template>
  <p class="panel-tabs">
    <a
      v-for="tab in tabs"
      :key="tab"
      href=""
      :class="{ 'is-active': tab === activeTab }"
      @click.prevent="$emit('switch', tab)"
      >{{ tab }}</a
    >
  </p>
</template>

<script lang="ts">
import { defineComponent } from "vue"

export default defineComponent({
  name: "TreatsTabs",
  props: {
    activeTab: {
      type: String,
      default: "ALL",
    },
  },
  emits: ["switch"],
  data() {
    return {
      tabs: ["ALL", "DISCOUNTED"],
    }
  },
})
</script>
