// ui/web/src/components/TreatsPanel.vue
<template>
  <div class="panel">
    <TreatsSearch v-model:search="search" />
    <TreatsTabs :active-tab="activeTab" @switch="activeTab = $event" />
    <template v-if="filteredTreats.length">
      <TreatsItem
        v-for="treat in filteredTreats"
        :key="treat.id"
        :treat="treat"
        :is-deleting="isDeleting(treat.id)"
        @treat-delete="deleteTreat"
      />
    </template>
    <template v-else>
      <div class="panel-block">
        {{ emptyText }}
      </div>
    </template>
    <NewTreat v-model:url="newTreatURL" :is-loading="isCreating" @submit="createTreat" />
  </div>
</template>

<script lang="ts">
import TreatsItem from "./TreatsItem.vue"
import TreatsTabs from "./TreatsTabs.vue"
import TreatsSearch from "./TreatsSearch.vue"
import NewTreat from "./NewTreat.vue"
import { useTreatsStore } from "@/stores/treats"
import { defineComponent } from "vue"
import type { Treat } from "@/models/treat"

const notFound = "Ни одной вкусняшки не найдено"
const empty = "Пока не добавлено ни одной вкусняшки"

export default defineComponent({
  name: "TreatsPanel",
  components: {
    NewTreat,
    TreatsItem,
    TreatsTabs,
    TreatsSearch,
  },
  setup() {
    const treatsStore = useTreatsStore()
    return { treatsStore }
  },
  data: () => {
    return {
      isCreating: false,
      deleting: [] as number[],
      search: "",
      activeTab: "ALL",
      newTreatURL: "",
    }
  },
  computed: {
    filteredTreats(): Array<Treat> {
      return this.treatsStore.treats.filter(this.filterBySearch).filter(this.filterByTab)
    },
    emptyText(): string {
      return this.treatsStore.treats.length ? notFound : empty
    },
  },
  methods: {
    isDeleting(treatId: number) {
      return this.deleting.includes(treatId)
    },
    filterBySearch(treat: Treat) {
      if (!this.search) return true
      return treat.title.toLowerCase().includes(this.search.toLowerCase())
    },
    filterByTab(treat: Treat) {
      const discounted = (treat: Treat) => treat.oldPrice !== null && treat.price < treat.oldPrice

      switch (this.activeTab) {
        case "DISCOUNTED":
          return discounted(treat)
        default:
          return true
      }
    },
    async createTreat() {
      this.isCreating = true
      let error = false

      try {
        await this.treatsStore.createTreat(this.newTreatURL)
      } catch (e) {
        error = true
        throw e
      } finally {
        this.isCreating = false

        if (!error) this.newTreatURL = ""
      }
    },
    async deleteTreat(id: number) {
      this.deleting.push(id)

      try {
        await this.treatsStore.deleteTreat(id)
      } finally {
        this.deleting = this.deleting.filter((id_) => id_ !== id)
      }
    },
  },
})
</script>

// ui/web/src/components/TreatsPanel.svelte
<div class="panel">
  <TreatsHeading/>
  <TreatsSearch on:search={setSearch}/>
  <TreatsTabs on:switch={setTab} bind:currentTab={currentTab}/>
  {#each filteredTreats as treat}
    <TreatItem {...treat} on:delete={deleteTreat} isLoading="{isDeleting(treat.id)}"/>
  {:else}
    <div class="panel-block">{emptyText}</div>
  {/each}
  <TreatNew on:add={createTreat} isLoading="{isCreating}" shops={shops}/>
</div>

<script>
  import {onMount} from "svelte"
  import TreatsHeading from "./TreatsHeading.svelte"
  import TreatsSearch from "./TreatsSearch.svelte"
  import TreatsTabs from "./TreatsTabs.svelte"
  import TreatItem from "./TreatItem.svelte"
  import TreatNew from "./TreatNew.svelte"
  import {Tab} from "../const.js"
  import treatService from "../services/api.js"

  export let apiService
  let isCreating = false
  let isDeletingList = []
  let treats = []
  let shops = []
  let search = '';
  let currentTab = Tab.ALL

  onMount(async () => {
    shops = await apiService.listShops().json()
    treats = await apiService.listUserTreats().json()
    treats.forEach(treat => {
      treat.shopName = shops.find(shop => shop.id === treat['shop_id']).name
      treat.lastPrice = treat['last_price']
      delete treat['last_price']
      delete treat['shop_id']
    })
  })

  const bySearch = (treat) => {
    if (!search) true
    return treat.title.toLowerCase().includes(search.toLowerCase())
  }

  const byTab = (treat) => {
    const discounted = (treat) => (treat.oldPrice !== null) && (treat.price < treat.oldPrice)

    switch (currentTab) {
      case Tab.DISCOUNTED:
        return discounted(treat)
      default:
        return true
    }
  }

  const setSearch = (event) => {
    search = event.detail
  }

  const setTab = (event) => {
    currentTab = event.detail
  }

  const deleteTreat = async (event) => {
    isDeletingList = [...isDeletingList, event.detail]
    await apiService.deleteTreat(event.detail)
    isDeletingList = isDeletingList.filter((id) => id !== event.detail)
    treats = treats.filter((treat) => treat.id !== event.detail)
  }

  const createTreat = async (event) => {
    isCreating = true

    try {
      const response = await apiService.createTreat(event.detail)
      treats = [...treats, await response.json()]
    } finally {
      isCreating = false
    }
  }

  const notFound = 'Ни одной вкусняшки не найдено'
  const empty = 'Пока не добавлено ни одной вкусняшки'

  $: filteredTreats = treats.filter((treat) => bySearch(treat, search)).filter((treat) => byTab(treat, currentTab))
  $: emptyText = search || currentTab !== Tab.ALL ? notFound : empty
  $: isDeleting = (id) => isDeletingList.includes(id)
</script>
